version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
          - "major"
          - "security"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
