name: Tests
on: push
jobs:
  code-style:
    name: Code style
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        cache: 'pip'
    - run: pip install poetry
    - name: Install dependencies
      run: poetry install
    - name: Check code style
      run: poetry run black . --check
